name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests
        pip install datetime
        pip install pytz
        pip install tqdm
    
    - name: Prepare source with token
      shell: pwsh
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        $content = Get-Content -Path update.py -Raw
        $escapedToken = $env:TOKEN -replace '\\', '\\' -replace '"', '\"'
        $content = $content -replace 'GITHUB_TOKEN_PLACEHOLDER', $escapedToken
        Set-Content -Path update.py -Value $content
    
    - name: Build executable
      run: |
        pyinstaller --onefile --clean update.py
    
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: update-windows
        path: dist/
        
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests
        pip install datetime
        pip install pytz
        pip install tqdm
    
    - name: Prepare source with token
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        escaped_token=$(echo "$TOKEN" | sed 's/[\/&]/\\&/g')
        sed -i.bak "s/GITHUB_TOKEN_PLACEHOLDER/$escaped_token/g" update.py
    
    - name: Build executable
      run: |
        pyinstaller --onefile --clean update.py
    
    - name: Upload macOS executable
      uses: actions/upload-artifact@v4
      with:
        name: update-macos
        path: dist/
